//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SB.Migrator.SqlServer.ResxFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SB.Migrator.SqlServer.ResxFiles.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM INFORMATION_SCHEMA.COLUMNS.
        /// </summary>
        internal static string SelectColumns {
            get {
                return ResourceManager.GetString("SelectColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    f.name as CONSTRAINT_NAME
        ///   ,OBJECT_SCHEMA_NAME(f.parent_object_id) AS REFERENCING_TABLE_SCHEMA_NAME
        ///   ,OBJECT_NAME(f.parent_object_id) AS REFERENCING_TABLE_NAME
        ///   ,COL_NAME(fc.parent_object_id, fc.parent_column_id) AS REFERENCING_COLUMN_NAME 
        ///   ,OBJECT_SCHEMA_NAME (f.referenced_object_id) AS REFERENCED_TABLE_SCHEMA_NAME
        ///   ,OBJECT_NAME (f.referenced_object_id) AS REFERENCED_TABLE_NAME
        ///   ,COL_NAME(fc.referenced_object_id, fc.referenced_column_id) AS REFERENCED_COLUMN_NAME
        ///   ,delete_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectForeignKeys {
            get {
                return ResourceManager.GetString("SelectForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT KU.TABLE_SCHEMA, KU.TABLE_NAME, COLUMN_NAME, TC.CONSTRAINT_NAME
        ///FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC
        ///INNER JOIN
        ///INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KU
        ///ON TC.CONSTRAINT_TYPE = &apos;PRIMARY KEY&apos; AND
        ///TC.CONSTRAINT_NAME = KU.CONSTRAINT_NAME;.
        /// </summary>
        internal static string SelectPrimaryKeys {
            get {
                return ResourceManager.GetString("SelectPrimaryKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_SCHEMA, TABLE_NAME 
        ///FROM INFORMATION_SCHEMA.TABLES     
        ///WHERE TABLE_TYPE=&apos;BASE TABLE&apos;.
        /// </summary>
        internal static string SelectTables {
            get {
                return ResourceManager.GetString("SelectTables", resourceCulture);
            }
        }
    }
}
