//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SB.Common.Test.Logics.TextParsers.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextParserTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextParserTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SB.Common.Test.Logics.TextParsers.Helpers.TextParserTexts", typeof(TextParserTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КАСБ-КОРГА ҚОДИР БЎЛГАН, СОҒЛОМ УКАМГА ЗАКОТ БЕРСАМ БЎЛАДИМИ?
        ///
        ///@Savollar_kanal 8863-савол
        ///
        ///Ассалому алайкум! Закотни ака-укага берса бўлар экан. Менинг укам намоз ўқимайди. Ўзининг уйи, оиласи бор, ўзи соғлом, икки нафар фарзанди бор. Рўзғори алоҳида. Ишчи бўлиб ишлайди. 2млн атрофида ойлик олади. Раҳбари талабига кўра ҳафтасига 7 кун ишлайди (ҳатто Ҳайит кунлари ҳам). Мен бермоқчи бўлган закот билан ҳам пули нисобга етмайди. “Мўминнинг нажоти” китоби “Закот олиши мумкин бўлмаганлар” боби 140-саҳифада “ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestText {
            get {
                return ResourceManager.GetString("TestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Forwarded from Fotiha.uz]
        ///@Savollar_kanal
        ///11-савол
        ///Кимларга салом бериш мумкин эмас?
        ///
        ///AZIZXONXXX · 20/07/2014 ·
        ///
        ///Ассалому алайкум, ҳурматли Шайх Ҳазратлари! Кимларга салом бериш мумкин ёки керак эмас?
        ///
        ///ЖАВОБ
        ///
        ///— Ношаръий ишларни қилиб турганларга.
        ///
        ///Шайх Муҳаммад Содиқ Муҳаммад Юсуф
        ///
        ///http://savollar.islom.uz/savol-29094/.
        /// </summary>
        internal static string TestTextOldVersion {
            get {
                return ResourceManager.GetString("TestTextOldVersion", resourceCulture);
            }
        }
    }
}
