name: publish SB.Auto.DependencyInjection to nuget
on:
  push:
    branches:
      - master-sb-auto-di # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish SB.Auto.DependenyInjection on version change
        id: publish_nuget_SB_Auto_DependenyInjection
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/DependecyInjection/SB.Auto.DependenyInjection/SB.Auto.DependenyInjection.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - uses: actions/checkout@v2
      - name: publish SB.Auto.DependecyInjection.AspNetCore on version change
        id: publish_nuget_SB_Auto_DependecyInjection_AspNetCore
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/DependecyInjection/SB.Auto.DependecyInjection.AspNetCore/SB.Auto.DependecyInjection.AspNetCore.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - uses: devmasx/merge-branch@v1.3.1
        name: Merge development -> master
        with:
          type: now
          target_branch: master
          github_token: ${{ github.token }}
      
      - uses: up9cloud/action-notify@master
        name: Notify Telegram
        if: always()
        env:
          GITHUB_JOB_STATUS: ${{ job.status }}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_USER}}