name: publish SB.Report to nuget
on:
  push:
    branches:
      - master-sb-report # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: rohith/publish-nuget@v2
        name: publish on version change
        with:
          PROJECT_FILE_PATH: src/SB.Report/SB.Report.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - uses: devmasx/merge-branch@v1.3.1
        name: Merge development -> master
        with:
          type: now
          target_branch: master
          github_token: ${{ github.token }}
      
      - uses: up9cloud/action-notify@master
        name: Notify Telegram
        if: always()
        env:
          GITHUB_JOB_STATUS: ${{ job.status }}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_USER}}