name: Publish SB.CodeMigration packages to NuGet

on:
  push:
    branches:
      - master-sb-code-migration

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # 1. Kodni yuklash
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. .NET SDK ni o‘rnatish
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # =====================
      # SB.CodeMigration
      # =====================
      - name: Restore SB.CodeMigration
        run: dotnet restore src/CodeMigration/SB.CodeMigration/SB.CodeMigration.csproj

      - name: Build SB.CodeMigration
        run: dotnet build -c Release src/CodeMigration/SB.CodeMigration/SB.CodeMigration.csproj --no-restore

      - name: Pack SB.CodeMigration
        run: dotnet pack -c Release src/CodeMigration/SB.CodeMigration/SB.CodeMigration.csproj -o ./artifacts --no-build

      - name: Push SB.CodeMigration to NuGet
        run: |
          dotnet nuget push ./artifacts/SB.CodeMigration.*.nupkg \
            --api-key ${{secrets.NUGET_API_KEY}} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate

      # =====================
      # SB.CodeMigration.AspNetCore
      # =====================
      - name: Restore SB.CodeMigration.AspNetCore
        run: dotnet restore src/CodeMigration/SB.CodeMigration.AspNetCore/SB.CodeMigration.AspNetCore.csproj

      - name: Build SB.CodeMigration.AspNetCore
        run: dotnet build -c Release src/CodeMigration/SB.CodeMigration.AspNetCore/SB.CodeMigration.AspNetCore.csproj --no-restore

      - name: Pack SB.CodeMigration.AspNetCore
        run: dotnet pack -c Release src/CodeMigration/SB.CodeMigration.AspNetCore/SB.CodeMigration.AspNetCore.csproj -o ./artifacts --no-build

      - name: Push SB.CodeMigration.AspNetCore to NuGet
        run: |
          dotnet nuget push ./artifacts/SB.CodeMigration.AspNetCore.*.nupkg \
            --api-key ${{secrets.NUGET_API_KEY}} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate

      # =====================
      # Merge development -> master
      # =====================
      - name: Merge development -> master
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: master
          github_token: ${{ github.token }}

      # =====================
      # Notify Telegram
      # =====================
      - name: Notify Telegram
        uses: up9cloud/action-notify@master
        if: always()
        env:
          GITHUB_JOB_STATUS: ${{ job.status }}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_USER}}
